server:
  port: 8101
  servlet:
    encoding:
      force-response: true
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

---
spring:
  config:
    activate:
      on-profile: local
  #profiles: local
  datasource:
    url: jdbc:mariadb://localhost:3306/ycchang
    driver-class-name: org.mariadb.jdbc.Driver
    username: ycchang
    password: init1234!
  #config:
  #  import:
  #      - classpath:/application-app.yml
  output:
    ansi:
      enable: ALWAYS
  jpa:
    open-in-view: true
    hibernate:
      #ddl-auto: create
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true
      #dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      dialect: org.hibernate.dialect.MariaDB103Dialect
    defer-datasource-initialization: true
    # auto relload
  thymeleaf:
    cache: false
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
    freemarker:
      cache: false
    thymeleaf:
      cache: false


mybatis:
  configuration:
    multiple-result-sets-enabled: false
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    jdbc-type-for-null: varchar
    default-fetch-size: 500
  mapper-locations:
    - classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis-config.xml.bak

logging:
  config: classpath:log4j2.yml
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

#security 기본 인증 옵션
security:
  basic:
    enabled: false

# cors 설정
cors:
  allowed-origins: 'http://localhost:8080'
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: '*'
  max-age: 3600

server:
  port: 8101


---
spring:
  config:
    activate:
      on-profile: dev
  #profiles: local
  datasource:
    url: jdbc:mariadb://localhost:3306/DB_TEST
    driver-class-name: org.mariadb.jdbc.Driver
    username: ycchang
    password: init1234!
  #config:
  #  import:
  #      - classpath:/application-app.yml
  output:
    ansi:
      enable: ALWAYS
  jpa:
    open-in-view: true
    hibernate:
      #ddl-auto: create
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true
      #dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      dialect: org.hibernate.dialect.MariaDB103Dialect
    defer-datasource-initialization: true

logging:
  config: classpath:log4j2.yml
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

jwt:
  header: Authorization
  secret: fsdfsaSDFSADFADAAAABBB1235214adsfasdfadsfdafadfsudbvcxvbxcbbBCCCCDDDDEEEEFFFFGGGG123!@#!@#!@$!@%!@$!@#!%@asdfasSFAFWEVxcVZvc1@EE!F@4fEs
  token-validity-in-seconds: 86400  #토큰 유효시간


server:
  port: 8102
#port: 80

---
spring:
  config:
    activate:
      on-profile: prod
  #profiles: local
  datasource:
    url: jdbc:mariadb://localhost:3306/DB_TEST
    driver-class-name: org.mariadb.jdbc.Driver
    username: ycchang
    password: init1234!
  #config:
  #  import:
  #      - classpath:/application-app.yml
  output:
    ansi:
      enable: ALWAYS
  jpa:
    open-in-view: true
    hibernate:
      #ddl-auto: create
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true
      #dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      dialect: org.hibernate.dialect.MariaDB103Dialect
    defer-datasource-initialization: true

logging:
  config: classpath:log4j2.yml
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

server:
  port: 8102